#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <cartrack_app_icons.h>

int32_t cartrack_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm cartrack_app!");

    return 0;
}
